[package]
name = "irc_mio"
version = "0.1.0"
authors = ["Stacey Ell <stacey.ell@gmail.com>"]

[dependencies.irc]
git = "https://github.com/infinityb/rust-irc"

[dependencies.mio]
git = "https://github.com/carllerche/mio"

[dependencies.bytes]
git = "https://github.com/carllerche/bytes"